# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-24 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurent', '0003_auto_20180724_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurentlocation',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='restaurentlocation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurentlocation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
