# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-25 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurent', '0004_auto_20180724_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurentlocation',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
