# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-27 11:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurent', '0005_restaurentlocation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurentlocation',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
